require_relative '../src/webrake'
include Webrake

task :default => ['build']

Site.new(
  Rake.application, 
  FileSystem.new('actual'),
  :dependencies => {
    ['typography.less', 'reset.less'] => 'concatenated_style.css.less'
  },
  :filters => { 
    '*.erb' => Filters::Erb.new, 
    '*.css.less' => Filters::Less.new
  #TODO: test glob ordering somewhere!!
  },
  :output => { 
    '*.html' => Layout::Erb.new('actual/layout/default.html.erb'),
    'blog/*.html' => Layout::Erb.new('actual/layout/blog.html.erb')
  }
)

#puts Rake.application.tasks.map(&:inspect).join("\n")
task :build_clean => ['clean', 'build']
