require_relative '../src/webrake'

task :default => ['build']

Webrake.new(
  Rake.application, 
  FileSystem.new,
  :filters => { '*.html.erb' => Filters::PassThroughFilter.new }
 # ,:copy => { '*.html' => 'output/' }
)

#puts Rake.application.tasks.inspect
task :clean => 'clean_intermediate_files'
task :build_clean => ['clean', 'build']
