require_relative '../src/webrake'

task :default => ['make']

Rules.new(Rake.application, FileSystem.new, {
  'index.html.erb' => Filters::PassThroughFilter.new
})

task :make_clean => ['clean_intermediate_files', 'make']
task :make => 'source/index.html'
