require_relative '../lib/webrake'
include Webrake

task :default => ['build']

Site.new(Rake.application, FileSystem.new('actual')) do |s|
  s.dependencies(
    ['typography.less', 'reset.less'] => 'concatenated_style.css.less',
    '*.html' => 'sitemap.txt')

  s.filters(
    '*.erb' => Filters::Erb.new, 
    '*.css.less' => Filters::Less.new)

  s.output(
    '*.html' => Layout::Erb.new('actual/layout/default.html.erb'),  # don't specify actual here
    'blog/*.html' => Layout::Erb.new('actual/layout/blog.html.erb'))
end



#puts Rake.application.tasks.map(&:inspect).join("\n")
task :build_clean => ['clean', 'build']
