require_relative '../../lib/webrake'
include Webrake

task :default => ['build']

Site.new(
  Rake.application, 
  FileSystem.new('.'),
  :dependencies => {
    ['typography.less', 'reset.less'] => 'concatenated_style.css.less',
    '*.html' => 'sitemap.txt',
    'blog/*.html' => 'blog_summary.html'
  },
  :filters => { 
    '*.erb' => Filters::Erb.new, 
    '*.markdown' => Filters::Kramdown.new, 
    '*.css.less' => Filters::Less.new('source')
  },
  :output => { 
    '*.html' => Layout::Erb.new('layout/default.html.erb'), 
    'blog/*.html' => Layout::Erb.new('layout/blog.html.erb'),
    '*.jpg' => Layout::None
  }
)

#puts Rake.application.tasks.map(&:inspect).join("\n")
task :build_clean => ['clean', 'build']
